version: '3.8'

networks:
  delivery-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    networks:
      delivery-network:
        aliases:
          - db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres